version: '3'

services:
  postgresql:
    image: bitnami/postgresql
    container_name: db_postgresql_find_a_friend
    restart: always
    ports:
      - "5480:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=findAFriend
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - api-findAFriend

  api:
    image: node:18
    container_name: api_find_a_friend
    depends_on:
      - postgresql
    restart: always
    working_dir: /build
    command: bash -c "npm install && npm run npx && npm run start"
    volumes:
      - ./build/:/build/
      - ./package.json:/package.json
      - ./package-lock.yaml:/package-lock.yaml
      - ./prisma:/prisma
      - ./.env:/.env
    networks:
      - api-findAFriend
    ports:
      - "3333:3333"

volumes:
  dbdata:
    name: postgresql_find_a_friend
    external: false
networks:
  api-findAFriend:
    name: api-findAFriend
    driver: bridge
    external: false
